### ISSUE TITLE
Version declaration 

### ISSUE THREAD

**Issue by zhangzhili000** [PlatONnetwork/browser-server#115]
In validator detail page's behavior tag, there is no version declaration action. Could you please show this action?

**Comment by biganxin** [comment]
@HYPWolf 
Suggest adding relevant tags to issues, example,bug, help wanted ,good first issue ...
Ditto for other issues

**Comment by zhouxi-jzheng** [comment]
当前浏览器在节点详情中可以展示节点版本版本声明的信息
