### ISSUE TITLE
PlatON Devnet2Scan PRC20的总量与分量总和展示不相匹配

### ISSUE THREAD

**Issue by RyannnQAQ** [PlatONnetwork/browser-server#180]
围观网址：https://devnet2scan.platon.network/tokens-detail?address=lat162edgqr5mfsgg669v02a0qz7krmqun9aghl5qp

此处的总量是 8.98，但是分量之和是 8.99，展示有误差。

![image](https://github.com/PlatONnetwork/browser-server/assets/133073425/03d3d55a-6b06-4bb8-aef5-d402758145bb)

**Comment by RyannnQAQ** [comment]
通过 F12 初步判断是对 balance 做保留两位小数的操作，导致四舍五入。

![image](https://github.com/PlatONnetwork/browser-server/assets/133073425/ad0b4ab8-faeb-4912-851e-53ab90ca7c31)

**Comment by chenxiaodai** [comment]
这个场景看也算正常的。不同界面显示精度要求不同， 金额省略都是截取方式。
